### ISSUE TITLE
Typos in built_in.any

### ISSUE THREAD

**Issue by Wikkedkain** [ylcnfrht/vscode-python-snippet-pack#1]
As you can see in the screenshot, there are two typos in the built_in.any example snippet.
![image](https://user-images.githubusercontent.com/8181070/56432791-c6b9db00-629c-11e9-9cea-52ce84d414be.png)

The description states "An example for using all with list" and the actual snippet outputs "ant" instead of "any".

Thank you

**Comment by ylcnfrht** [comment]
I update it.
Thank you for your comment.
